### ISSUE TITLE
No module named mayavi.spheres

### ISSUE THREAD

**Issue by Phocion** [Garyfallidis/dipy#11]
Greetings, all.  

It looks like from some discussions here, the API is currently being revamped a bit.  I'm running into some issues getting the imports right between the online examples and the ones provided in /doc/examples.  My knowledge of DIPY is limited, but trying to rectify the issues myself for the most past.

What version of Mayavi is supported?  Using 5.x, I get the exception that Mayavi is not installed.  Using 4.2.0, I get the following error in nii_2_tracks.py:

Traceback (most recent call last):
  File "doc/examples/nii_2_tracks.py", line 174, in <module>
    from dipy.viz import fvtk
  File "/usr/local/lib/python2.7/dist-packages/dipy/viz/**init**.py", line 30, in <module>
    from .mayavi.spheres import show_odfs
ImportError: No module named mayavi.spheres

Am I using an incompatible version of Mayavi?   Thank you.

Whoops - too many tabs open.  Posted this in a fork.  Please disregard.

Appears to be a known issue already open in main branch: https://github.com/nipy/dipy/pull/125

**Comment by Garyfallidis** [comment]
Hi Tim,

Yes, indeed we know about the mayavi issue but thank you for the post anyway. There also new examples which are in agreement with the new API https://github.com/nipy/dipy/pull/123 You may want to have a look. We should be able to merge them in the main project (nipy/dipy) in a few days.

Concerning mayavi. The code show_odfs in mayavi.spheres should work with Mayavi 4.2+ and 5.x 

Best wishes,
Eleftherios

**Comment by Phocion** [comment]
Great, thanks Eleftherios!
